### ISSUE TITLE
SSH crashed for Welly on macOS 14 (23A5286i)

### ISSUE THREAD

**Issue by bzqlki** [ytang/welly#11]
升级到macOS 14 public beta后，发现ssh登录水木失败，窗口也没有出任何提示；换用telnet能上了。这个bug能修么？

**Comment by ytang** [comment]
我目前没有能用来安装测试版操作系统的电脑，所以要等到 Sonoma 正式版发布之后才能测试。请问您是用密码登录还是公钥登录 SSH 的？如果是前者，那大概率是 [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/) 的问题。不妨尝试一下使用公钥登录，设置方法参见[这个帖子](https://www.mysmth.net/nForum/article/Apple/1490952?s=1491192)。

**Comment by bzqlki** [comment]
多谢回复，我一会儿试试，看看改公钥登录能不能解决问题

**Comment by bzqlki** [comment]
换上述方法后公钥生成后可以登录水木了，但是每次登录的时候，都会出来一行错误提示，很快闪过了就。今天用quicktime录屏终于看见是什么了，下面这段文字（然后就是水木ssh登录后敲第一个回车的那个页面了）

tcsetattr: Operation not permitted

**Comment by ytang** [comment]
可以忽略这行字，不影响正常使用。
