### ISSUE TITLE
Cannot Connect to PTT in macOS 14.0 (23A339)

### ISSUE THREAD

**Issue by tyroneproctor** [ytang/welly#12]
It shows "App quit unexpectedly" and please find below for report:

> -------------------------------------
> Translated Report (Full Report Below)
> -------------------------------------
> 
> Process:               Welly [2537]
> Path:                  /Applications/Welly.app/Contents/MacOS/Welly
> Identifier:            com.ytang.Welly
> Version:               2022.2 (1021)
> App Item ID:           1521402269
> App External ID:       848318784
> Code Type:             ARM-64 (Native)
> Parent Process:        Welly [2497]
> Responsible:           Welly [2497]
> User ID:               501
> 
> Date/Time:             2023-09-21 00:14:52.5885 +0800
> OS Version:            macOS 14.0 (23A339)
> Report Version:        12
> Anonymous UUID:        594963A4-6852-43C0-49E1-C6C86CA1F7BE
> 
> 
> Time Awake Since Boot: 2700 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000100680dac
> Exception Codes:       0x0000000000000001, 0x0000000100680dac
> 
> Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
> Terminating Process:   exc handler [2537]
> 
> VM Region Info: 0x100680dac is not in any region.  Bytes after previous region: 3501  Bytes before following region: 258644
>       REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
>       MALLOC metadata             10067c000-100680000    [   16K] rw-/rwx SM=COW  
> --->  GAP OF 0x40000 BYTES
>       shared memory               1006c0000-1006c4000    [   16K] r--/r-- SM=SHM  
> 
> Application Specific Information:
> *** multi-threaded process forked ***
> crashed on child side of fork pre-exec
> 
> 
> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   libsystem_trace.dylib         	       0x1896e723c _os_log_preferences_refresh + 68
> 1   libsystem_trace.dylib         	       0x1896e7c9c os_log_type_enabled + 712
> 2   CoreFoundation                	       0x189a29214 _CFBundleCopyFindResources + 2264
> 3   CoreFoundation                	       0x189a2892c CFBundleCopyResourceURL + 56
> 4   Foundation                    	       0x18ab17fc4 -[NSBundle URLForResource:withExtension:subdirectory:] + 96
> 5   Foundation                    	       0x18ab325d0 -[NSBundle pathForResource:ofType:] + 36
> 6   Welly                         	       0x1001179b8 0x100114000 + 14776
> 7   Welly                         	       0x100117de8 0x100114000 + 15848
> 8   Welly                         	       0x10011f054 0x100114000 + 45140
> 9   Welly                         	       0x10011efa0 0x100114000 + 44960
> 10  Welly                         	       0x1001319fc 0x100114000 + 121340
> 11  AppKit                        	       0x18d3de7e8 -[NSApplication(NSResponder) sendAction:to:from:] + 460
> 12  AppKit                        	       0x18d4a8a68 -[NSMenuItem _corePerformAction] + 372
> 13  AppKit                        	       0x18da36408 _NSMenuPerformActionWithHighlighting + 152
> 14  AppKit                        	       0x18d8b5494 -[NSMenu _performActionForItem:atIndex:fromEvent:] + 212
> 15  AppKit                        	       0x18d4a7c84 -[NSMenu performKeyEquivalent:] + 356
> 16  AppKit                        	       0x18da0d818 routeKeyEquivalent + 444
> 17  AppKit                        	       0x18da0b918 -[NSApplication(NSEventRouting) sendEvent:] + 652
> 18  AppKit                        	       0x18d65f318 -[NSApplication _handleEvent:] + 60
> 19  AppKit                        	       0x18d22c5bc -[NSApplication run] + 512
> 20  AppKit                        	       0x18d203864 NSApplicationMain + 880
> 21  dyld                          	       0x189609058 start + 2224
> 
> 
> Thread 0 crashed with ARM Thread State (64-bit):
>     x0: 0x00000001e0c453ac   x1: 0x0000000000000000   x2: 0x00000001896e4c5c   x3: 0x0000000000000004
>     x4: 0x0000000000044000   x5: 0x0000000000000001   x6: 0x0000000000000002   x7: 0x0000000000000008
>     x8: 0x0000000100680daa   x9: 0x00000001e0c4f9d0  x10: 0x0000000000000001  x11: 0x0000600003f6cb30
>    x12: 0x0000000000000001  x13: 0x0000000000000003  x14: 0x000000012e900000  x15: 0x00000000448176b1
>    x16: 0x0000000189943294  x17: 0x00000001e9e74cb0  x18: 0x0000000000000000  x19: 0x0000600003f6cb00
>    x20: 0x0000600003f6cb00  x21: 0x0000000100680dae  x22: 0x0000000100680dae  x23: 0x0000600001368000
>    x24: 0x920bf3e12a2e6204  x25: 0x0000000000000001  x26: 0x0000000000000000  x27: 0x0000000000000000
>    x28: 0x00006000013680c8   fp: 0x000000016fcea730   lr: 0x00000001896e7220
>     sp: 0x000000016fcea6e0   pc: 0x00000001896e723c cpsr: 0x20001000
>    far: 0x0000000100680dac  esr: 0x92000007 (Data Abort) byte read Translation fault
> 
> Binary Images:
>        0x10040c000 -        0x100417fff libobjc-trampolines.dylib (*) <562f95b3-8118-3d61-a13f-34e819dd863d> /usr/lib/libobjc-trampolines.dylib
>        0x100720000 -        0x10075bfff de.monscheuer.MMTabBarView (2022.2) <d4a1d923-5fa6-30b4-af21-1076270bddbe> /Applications/Welly.app/Contents/Frameworks/MMTabBarView.framework/Versions/A/MMTabBarView
>        0x100114000 -        0x10017ffff com.ytang.Welly (2022.2) <947cb27e-a725-3acf-bd76-29075fdd3fa8> /Applications/Welly.app/Contents/MacOS/Welly
>        0x1896e3000 -        0x1896fdfff libsystem_trace.dylib (*) <4af0ea7d-e9f4-30e7-914d-fb292edb7f37> /usr/lib/system/libsystem_trace.dylib
>        0x1899e2000 -        0x189eb8fff com.apple.CoreFoundation (6.9) <a68b8c77-1dbd-35b0-83fe-42ad58dd6629> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>        0x18ab0b000 -        0x18b75dfff com.apple.Foundation (6.9) <11eb37ae-355b-3a35-af1b-13b599244410> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
>        0x18d1ff000 -        0x18e50ffff com.apple.AppKit (6.9) <6cb2526d-d63b-3c9f-93a6-27887031c8b2> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
>        0x189603000 -        0x189696873 dyld (*) <ee3f4181-cec5-38c2-b8a8-4d310be33491> /usr/lib/dyld
>                0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
>        0x189941000 -        0x18997bfef libsystem_kernel.dylib (*) <57eb8ba7-205a-342c-a330-940db07cbcfd> /usr/lib/system/libsystem_kernel.dylib
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
> 
> VM Region Summary:
> ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
> Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)
> 
>                                 VIRTUAL   REGION 
> REGION TYPE                        SIZE    COUNT (non-coalesced) 
> ===========                     =======  ======= 
> Accelerate framework               128K        1 
> Activity Tracing                   256K        1 
> CG image                          18.3M       20 
> ColorSync                          560K       26 
> CoreAnimation                     7552K      103 
> CoreGraphics                        16K        1 
> CoreUI image data                 3664K       28 
> Foundation                          16K        1 
> Kernel Alloc Once                   32K        1 
> MALLOC                             1.4G       52 
> MALLOC guard page                  192K       12 
> STACK GUARD                       56.0M        1 
> Stack                             10.1M        5 
> Stack Guard                         64K        4 
> VM_ALLOCATE                         64K        4 
> __AUTH                            1656K      325 
> __AUTH_CONST                      27.0M      528 
> __CTF                               824        1 
> __DATA                            12.6M      517 
> __DATA_CONST                      26.7M      536 
> __DATA_DIRTY                      1700K      192 
> __FONT_DATA                        2352        1 
> __LINKEDIT                       886.7M        4 
> __OBJC_RO                         70.6M        1 
> __OBJC_RW                         2153K        1 
> __TEXT                           590.0M      553 
> dyld private memory                272K        2 
> mapped file                      294.2M       46 
> shared memory                      352K       18 
> ===========                     =======  ======= 
> TOTAL                              3.3G     2985 
> 
> 
> 
> -----------
> Full Report
> -----------
> 
> {"app_name":"Welly","timestamp":"2023-09-21 00:14:52.00 +0800","app_version":"2022.2","slice_uuid":"947cb27e-a725-3acf-bd76-29075fdd3fa8","adam_id":"1521402269","build_version":"1021","platform":1,"bundleID":"com.ytang.Welly","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A339)","roots_installed":0,"name":"Welly","incident_id":"DCB6FA1F-4E50-4FFA-9F84-BE1B7D678F04"}
> {
>   "uptime" : 2700,
>   "procRole" : "Unspecified",
>   "version" : 2,
>   "userID" : 501,
>   "deployVersion" : 210,
>   "modelCode" : "Macmini9,1",
>   "coalitionID" : 2386,
>   "osVersion" : {
>     "train" : "macOS 14.0",
>     "build" : "23A339",
>     "releaseType" : "User"
>   },
>   "captureTime" : "2023-09-21 00:14:52.5885 +0800",
>   "codeSigningMonitor" : 1,
>   "incident" : "DCB6FA1F-4E50-4FFA-9F84-BE1B7D678F04",
>   "pid" : 2537,
>   "translated" : false,
>   "cpuType" : "ARM-64",
>   "roots_installed" : 0,
>   "bug_type" : "309",
>   "procLaunch" : "2023-09-21 00:14:52.5830 +0800",
>   "procStartAbsTime" : 66442753898,
>   "procExitAbsTime" : 66442875658,
>   "procName" : "Welly",
>   "procPath" : "\/Applications\/Welly.app\/Contents\/MacOS\/Welly",
>   "bundleInfo" : {"CFBundleShortVersionString":"2022.2","CFBundleVersion":"1021","CFBundleIdentifier":"com.ytang.Welly"},
>   "storeInfo" : {"storeCohortMetadata":"10|date=1675490400000&sf=143470&pgtp=Software&pgid=1521402269&prpg=VersionHistory_1521402269&ctxt=Discover&lngid=18","itemID":"1521402269","deviceIdentifierForVendor":"E6D6E880-056A-5B3A-9E64-161CFB28016B","thirdParty":true,"softwareVersionExternalIdentifier":"848318784"},
>   "parentProc" : "Welly",
>   "parentPid" : 2497,
>   "coalitionName" : "com.ytang.Welly",
>   "crashReporterKey" : "594963A4-6852-43C0-49E1-C6C86CA1F7BE",
>   "responsiblePid" : 2497,
>   "responsibleProc" : "Welly",
>   "codeSigningID" : "com.ytang.Welly",
>   "codeSigningTeamID" : "AALZJYW2AF",
>   "codeSigningFlags" : 570442241,
>   "codeSigningValidationCategory" : 4,
>   "codeSigningTrustLevel" : 4294967295,
>   "instructionByteStream" : {"beforePC":"\/UMBkfMDAKovTgCUGQBAufMMALRoDkD5FREAkR8BAPH2A5WaSAwAtA==","atPC":"CQlAOQgBCYsUEQCR\/wcA+QirK5AAdUX5wAEAtOEDFqqrUQCU9wMAqg=="},
>   "sip" : "enabled",
>   "vmRegionInfo" : "0x100680dac is not in any region.  Bytes after previous region: 3501  Bytes before following region: 258644\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC metadata             10067c000-100680000    [   16K] rw-\/rwx SM=COW  \n--->  GAP OF 0x40000 BYTES\n      shared memory               1006c0000-1006c4000    [   16K] r--\/r-- SM=SHM  ",
>   "exception" : {"codes":"0x0000000000000001, 0x0000000100680dac","rawCodes":[1,4301786540],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000100680dac"},
>   "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":2537},
>   "vmregioninfo" : "0x100680dac is not in any region.  Bytes after previous region: 3501  Bytes before following region: 258644\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC metadata             10067c000-100680000    [   16K] rw-\/rwx SM=COW  \n--->  GAP OF 0x40000 BYTES\n      shared memory               1006c0000-1006c4000    [   16K] r--\/r-- SM=SHM  ",
>   "asi" : {"CoreFoundation":["*** multi-threaded process forked ***"],"libsystem_c.dylib":["crashed on child side of fork pre-exec"]},
>   "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
>   "faultingThread" : 0,
>   "threads" : [{"triggered":true,"id":49946,"threadState":{"x":[{"value":8065930156,"symbolLocation":172,"symbol":"_main_thread"},{"value":0},{"value":6600674396,"symbolLocation":0,"symbol":"_os_trace_init_slow"},{"value":4},{"value":278528},{"value":1},{"value":2},{"value":8},{"value":4301786538},{"value":8065972688,"symbolLocation":0,"symbol":"errno"},{"value":1},{"value":105553182772016},{"value":1},{"value":3},{"value":5076156416},{"value":1149335217},{"value":6603158164,"symbolLocation":0,"symbol":"__error"},{"value":8219217072},{"value":0},{"value":105553182771968},{"value":105553182771968},{"value":4301786542},{"value":4301786542},{"value":105553136615424},{"value":10523773102682169860},{"value":1},{"value":0},{"value":0},{"value":105553136615624}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6600684064},"cpsr":{"value":536875008},"fp":{"value":6170781488},"sp":{"value":6170781408},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6600684092,"matchesCrashFrame":1},"far":{"value":4301786540}},"queue":"com.apple.main-thread","frames":[{"imageOffset":16956,"symbol":"_os_log_preferences_refresh","symbolLocation":68,"imageIndex":3},{"imageOffset":19612,"symbol":"os_log_type_enabled","symbolLocation":712,"imageIndex":3},{"imageOffset":291348,"symbol":"_CFBundleCopyFindResources","symbolLocation":2264,"imageIndex":4},{"imageOffset":289068,"symbol":"CFBundleCopyResourceURL","symbolLocation":56,"imageIndex":4},{"imageOffset":53188,"symbol":"-[NSBundle URLForResource:withExtension:subdirectory:]","symbolLocation":96,"imageIndex":5},{"imageOffset":161232,"symbol":"-[NSBundle pathForResource:ofType:]","symbolLocation":36,"imageIndex":5},{"imageOffset":14776,"imageIndex":2},{"imageOffset":15848,"imageIndex":2},{"imageOffset":45140,"imageIndex":2},{"imageOffset":44960,"imageIndex":2},{"imageOffset":121340,"imageIndex":2},{"imageOffset":1964008,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":460,"imageIndex":6},{"imageOffset":2792040,"symbol":"-[NSMenuItem _corePerformAction]","symbolLocation":372,"imageIndex":6},{"imageOffset":8614920,"symbol":"_NSMenuPerformActionWithHighlighting","symbolLocation":152,"imageIndex":6},{"imageOffset":7038100,"symbol":"-[NSMenu _performActionForItem:atIndex:fromEvent:]","symbolLocation":212,"imageIndex":6},{"imageOffset":2788484,"symbol":"-[NSMenu performKeyEquivalent:]","symbolLocation":356,"imageIndex":6},{"imageOffset":8448024,"symbol":"routeKeyEquivalent","symbolLocation":444,"imageIndex":6},{"imageOffset":8440088,"symbol":"-[NSApplication(NSEventRouting) sendEvent:]","symbolLocation":652,"imageIndex":6},{"imageOffset":4588312,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":6},{"imageOffset":185788,"symbol":"-[NSApplication run]","symbolLocation":512,"imageIndex":6},{"imageOffset":18532,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":6},{"imageOffset":24664,"symbol":"start","symbolLocation":2224,"imageIndex":7}]}],
>   "usedImages" : [
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 4299210752,
>     "size" : 49152,
>     "uuid" : "562f95b3-8118-3d61-a13f-34e819dd863d",
>     "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
>     "name" : "libobjc-trampolines.dylib"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64",
>     "base" : 4302438400,
>     "CFBundleShortVersionString" : "2022.2",
>     "CFBundleIdentifier" : "de.monscheuer.MMTabBarView",
>     "size" : 245760,
>     "uuid" : "d4a1d923-5fa6-30b4-af21-1076270bddbe",
>     "path" : "\/Applications\/Welly.app\/Contents\/Frameworks\/MMTabBarView.framework\/Versions\/A\/MMTabBarView",
>     "name" : "MMTabBarView",
>     "CFBundleVersion" : "1021"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64",
>     "base" : 4296097792,
>     "CFBundleShortVersionString" : "2022.2",
>     "CFBundleIdentifier" : "com.ytang.Welly",
>     "size" : 442368,
>     "uuid" : "947cb27e-a725-3acf-bd76-29075fdd3fa8",
>     "path" : "\/Applications\/Welly.app\/Contents\/MacOS\/Welly",
>     "name" : "Welly",
>     "CFBundleVersion" : "1021"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6600667136,
>     "size" : 110592,
>     "uuid" : "4af0ea7d-e9f4-30e7-914d-fb292edb7f37",
>     "path" : "\/usr\/lib\/system\/libsystem_trace.dylib",
>     "name" : "libsystem_trace.dylib"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6603808768,
>     "CFBundleShortVersionString" : "6.9",
>     "CFBundleIdentifier" : "com.apple.CoreFoundation",
>     "size" : 5074944,
>     "uuid" : "a68b8c77-1dbd-35b0-83fe-42ad58dd6629",
>     "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
>     "name" : "CoreFoundation",
>     "CFBundleVersion" : "2048.1.403"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6621802496,
>     "CFBundleShortVersionString" : "6.9",
>     "CFBundleIdentifier" : "com.apple.Foundation",
>     "size" : 12922880,
>     "uuid" : "11eb37ae-355b-3a35-af1b-13b599244410",
>     "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
>     "name" : "Foundation",
>     "CFBundleVersion" : "2048.1.403"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6662647808,
>     "CFBundleShortVersionString" : "6.9",
>     "CFBundleIdentifier" : "com.apple.AppKit",
>     "size" : 19992576,
>     "uuid" : "6cb2526d-d63b-3c9f-93a6-27887031c8b2",
>     "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
>     "name" : "AppKit",
>     "CFBundleVersion" : "2485"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6599749632,
>     "size" : 604276,
>     "uuid" : "ee3f4181-cec5-38c2-b8a8-4d310be33491",
>     "path" : "\/usr\/lib\/dyld",
>     "name" : "dyld"
>   },
>   {
>     "size" : 0,
>     "source" : "A",
>     "base" : 0,
>     "uuid" : "00000000-0000-0000-0000-000000000000"
>   },
>   {
>     "source" : "P",
>     "arch" : "arm64e",
>     "base" : 6603149312,
>     "size" : 241648,
>     "uuid" : "57eb8ba7-205a-342c-a330-940db07cbcfd",
>     "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
>     "name" : "libsystem_kernel.dylib"
>   }
> ],
>   "sharedCache" : {
>   "base" : 6599000064,
>   "size" : 4012507136,
>   "uuid" : "82432966-0197-3a07-bff2-d3c8205c5ed8"
> },
>   "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                          18.3M       20 \nColorSync                          560K       26 \nCoreAnimation                     7552K      103 \nCoreGraphics                        16K        1 \nCoreUI image data                 3664K       28 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.4G       52 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.0M        1 \nStack                             10.1M        5 \nStack Guard                         64K        4 \nVM_ALLOCATE                         64K        4 \n__AUTH                            1656K      325 \n__AUTH_CONST                      27.0M      528 \n__CTF                               824        1 \n__DATA                            12.6M      517 \n__DATA_CONST                      26.7M      536 \n__DATA_DIRTY                      1700K      192 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       886.7M        4 \n__OBJC_RO                         70.6M        1 \n__OBJC_RW                         2153K        1 \n__TEXT                           590.0M      553 \ndyld private memory                272K        2 \nmapped file                      294.2M       46 \nshared memory                      352K       18 \n===========                     =======  ======= \nTOTAL                              3.3G     2985 \n",
>   "legacyInfo" : {
>   "threadTriggered" : {
>     "queue" : "com.apple.main-thread"
>   }
> },
>   "logWritingSignature" : "89da856c842ed680fd47a499297db27fdda6715a",
>   "trialInfo" : {
>   "rollouts" : [
>     {
>       "rolloutId" : "639124e81d92412bfb4880b3",
>       "factorPackIds" : {
> 
>       },
>       "deploymentId" : 240000012
>     },
>     {
>       "rolloutId" : "6425c75e4327780c10cc4252",
>       "factorPackIds" : {
>         "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
>       },
>       "deploymentId" : 240000004
>     }
>   ],
>   "experiments" : [
> 
>   ]
> }
> }
> 
> Model: Macmini9,1, BootROM 10151.1.1, proc 8:4:4 processors, 8 GB, SMC 
> Graphics: Apple M1, Apple M1, Built-In
> Display: Q27B3M, 4096 x 2304, Main, MirrorOff, Online
> Memory Module: LPDDR4, Hynix
> AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jul  8 2023 18:08:48 version 18.20.438.0.7.8.162 FWID 01-f7533da5
> AirPort: 
> Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
> Network Service: Wi-Fi, AirPort, en1
> Network Service: iPhone 2, Ethernet, en12
> USB Device: USB31Bus
> USB Device: VLI Product String
> USB Device: USB31Bus
> USB Device: Gen1
> USB Device: USB30Bus
> USB Device: USB3.2 Hub
> USB Device: Razer Basilsk X HyperSpeed
> USB Device: USB2.1 Hub
> USB Device: iPhone
> Thunderbolt Bus: Mac mini, Apple Inc.
> Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by ytang** [comment]
Thanks for reporting. I don't have a Mac that can run a beta version of macOS, so I have to wait until Sonoma is released.
