### ISSUE TITLE
Welly repeated notifying "Welly needs to download the font stheiti" at opening

### ISSUE THREAD

**Issue by gitfourteen** [ytang/welly#3]
click download, wait and complete the download, nothing happened

**Comment by ytang** [comment]
Welly uses STHeiti by default, which can be configured in Welly's _Preferences - Fonts_. It is normal that macOS prompts you to download the font if it is not present on your system. However, after the font has been installed, this dialog should not reappear. You can manage all fonts [using the Font Book app on your Mac](https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac). Can you verify that STHeiti is not dimmed in the Font Book?

**Comment by gitfourteen** [comment]
Checked Font Book and found STHeiti include 2 subitems, Light(dimmed) and Regular.

so I download the Light and add STHeiti pack with + at toolbar, choosing Welly in the prompt window, and Open.

Hope this work.

**Comment by ytang** [comment]
Only STHeiti Regular is needed; Light is unnecessary. Since you already have this font installed, Welly should not complain about it.

If you ever see the same dialog popping up again, please open Font Book immediately and examine if STHeiti Regular is present. I suspect it might be removed by another application like some system cleaner apps.

**Comment by gitfourteen** [comment]
Need manually add font by `User` and can not validate font with `Computer`.
 
1. Choose `Computer` in the leftmost and find `STHeiti: Light/Regular`
<img width="231" alt="STHeiti_Computer" src="https://user-images.githubusercontent.com/22335780/107041333-5676a380-67fb-11eb-8568-c696fdc1d846.png">

2. Choose User in the leftmost column and click `+` in the toolbar; 
3. Choose `STHeiti Medium` in the prompt window (I guess this is for STHeiti Regular? Though `STHeiti Light` removed, there is still `STHeiti Light.ttc);
<img width="217" alt="STHeiti Medium ttc" src="https://user-images.githubusercontent.com/22335780/107040136-c552fd00-67f9-11eb-90b0-9ebf7faf2de1.png">

When complete installation, get 2 more font `Heiti SC/TC`
<img width="529" alt="add_font_to_User" src="https://user-images.githubusercontent.com/22335780/107039340-be77ba80-67f8-11eb-905a-588922f4d533.png">

**Comment by ytang** [comment]
STHeiti and Heiti SC are two different fonts. You can choose whichever font you like in Welly's _Preferences - Fonts_.
