### ISSUE TITLE
藍牙鍵盤 fn 鍵沒有反應

### ISSUE THREAD

**Issue by wind50321** [ytang/welly#6]
筆電本身鍵盤可以使用 fn + up/down 換頁
藍牙鍵盤 fn 鍵沒有反應，只會跳上/下一行

版本 2021.1 (Mac App Store)
鍵盤 Logitech K380
系統 MacOS 10.15.7

**Comment by ytang** [comment]
感謝您的報告，不過目前我沒有 K380 鍵盤可供測試，所以暫時無法修復。
作為替代方案，Pull Request #4 提出使用 alt + up/down 換頁。如果需要，我可以編譯一份新版本發佈到 App Store。

**Comment by wind50321** [comment]
好的，謝謝。

另外標題的 Welly > 關于 Welly，
希望修正為繁體中文。
